steps:
- id: Docker build
  name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', '${_REPO_REGION}/${_PROJ_ID}/${_REPO_NAME}/${_SERVICE_NAME}', '.']

- id: Container image push
  name: 'gcr.io/cloud-builders/docker'
  args: ['push', '${_REPO_REGION}/${_PROJ_ID}/${_REPO_NAME}/${_SERVICE_NAME}']

- id: Cloud run deploy
  name: 'gcr.io/cloud-builders/gcloud'
  args:
  - 'run'
  - 'deploy'
  - '${_SERVICE_NAME}'
  - '--image'
  - '${_REPO_REGION}/${_PROJ_ID}/${_REPO_NAME}/${_SERVICE_NAME}'
  - '--port'
  - '80'
  - '--region'
  - '${_REGION}'
  - '--platform'
  - 'managed'
  - '--allow-unauthenticated'
  # - '--service-account'
  # - '${_SERVICE_ACCOUNT}'
  - '--max-instances'
  - '5'
  - '--timeout'
  - '60'

images:
- ${_REPO_REGION}/${_PROJ_ID}/${_REPO_NAME}/${_SERVICE_NAME}


substitutions:
  _REPO_REGION: us-docker.pkg.dev
  _REPO_NAME: shiv-testing
  _SERVICE_NAME: wordpress-cr-testing
  _REGION: us-central1
  _PROJ_ID: sureel-test
  # _SERVICE_ACCOUNT: 