steps:
# Build the container image
# update the gcr.io/[project-id]/[build-image-name]
- id: publish to pubsub
  name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      # Get the Git username from the email address (assumes format "username@domain")
      # git_username=$(echo "$COMMIT_EMAIL" | cut -d "@" -f 1)
      # echo "$git_username"
      echo "-------------------------------------------------"  
      git_user_email="$BUILD_USER_EMAIL"
      git_user_id=$(echo "$git_user_email" | cut -d "@" -f 1)
      echo "Git User ID: $git_user_id"
      echo "--------------------------------------------------"


      git_commit_info=$(git show $COMMIT_SHA)
      echo "git_commit_info"
      git_author=$(echo "$git_commit_info" | grep -m 1 "Author:")
      echo "git_author"
      git_author_name=$(echo "$git_author" | sed 's/Author: //')
      echo "git_author_name"

    

# - id: Docker build
#   name: 'gcr.io/cloud-builders/docker'
#   args: ['build', '-t', '${_REPO_REGION}/${_PROJECT_ID}/${_REPO_NAME}/${_SERVICE_NAME}:${_TAG_NAME}', '.']

# # Push the container image to Artifact Registry
# - id: Container image push
#   name: 'gcr.io/cloud-builders/docker'
#   args: ['push', '${_REPO_REGION}/${_PROJECT_ID}/${_REPO_NAME}/${_SERVICE_NAME}:${_TAG_NAME}']

# - id: Cloud run deploy
#   name: google/cloud-sdk
#   args:
#   - gcloud
#   - run
#   - deploy
#   - ${_SERVICE_NAME}
#   - --image=${_REPO_REGION}/${_PROJECT_ID}/${_REPO_NAME}/${_SERVICE_NAME}:${_TAG_NAME}
#   - --region=${_REGION}
#   - --platform=managed
#   - --service-account=${_SERVICE_ACCOUNT}
#   - --max-instances=5
#   - --memory=512Mi
#   # - --vpc-connector=projects/${_HOST_PROJECT_ID}/locations/${_REGION}/connectors/${_VPC_CONNECTOR}
#   # - --ingress=all
#   #- --ingress=internal-and-cloud-load-balancing
#   # - --vpc-egress=all-traffic
#   - --allow-unauthenticated
#   - --port=80
# timeout: 3660s

# images:
# - ${_REPO_REGION}/${_PROJECT_ID}/${_REPO_NAME}/${_SERVICE_NAME}:${TAG_NAME}

# options:
#   logging: CLOUD_LOGGING_ONLY
  
# substitutions:
#   _REPO_REGION: us-docker.pkg.dev
#   _REPO_NAME: shiv-testing
#   _SERVICE_NAME: testing
#   _REGION: us-central1
#   _SERVICE_ACCOUNT: shiv-testing-account@sureel-test.iam.gserviceaccount.com
#   _PROJECT_ID: sureel-test
#   _TAG_NAME: shiv-image1 
  


  # 'gcr.io/_PROJECT_ID/IMAGE_NAME:TAG'

  # us-docker.pkg.dev/glb-chr-artifactory/shiv-testing:shiv-image
