steps:
# Build the container image
# update the gcr.io/[project-id]/[build-image-name]
- id: Docker build
  name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', '${_REPO_REGION}/${_PROJECT_ID}/${_REPO_NAME}/${_SERVICE_NAME}', '.']

# Push the container image to Artifact Registry
- id: Container image push
  name: 'gcr.io/cloud-builders/docker'
  args: ['push', '${_REPO_REGION}/${_PROJECT_ID}/${_REPO_NAME}/${_SERVICE_NAME}']

- id: Cloud run deploy
  name: google/cloud-sdk
  args:
  - gcloud
  - run
  - deploy
  - ${_SERVICE_NAME}
  - --image=${_REPO_REGION}/${_PROJECT_ID}/${_REPO_NAME}/${_SERVICE_NAME}
  - --region=${_REGION}
  - --platform=managed
  # - --service-account=${_SERVICE_ACCOUNT}
  - --max-instances=5
  - --memory=512Mi
  - --allow-unauthenticated
  - --port=80
  - --port=443
timeout: 3660s

images:
- ${_REPO_REGION}/${_PROJECT_ID}/${_REPO_NAME}/${_SERVICE_NAME}

options:
  logging: CLOUD_LOGGING_ONLY
  
substitutions:
  _REPO_REGION: us-docker.pkg.dev
  _REPO_NAME: shiv-testing
  _SERVICE_NAME: testing
  _REGION: us-central1
  # _SERVICE_ACCOUNT: shiv-testing-account@sureel-test.iam.gserviceaccount.com
  _PROJECT_ID: sureel-test
  
