steps:
# Build the container image
# update the gcr.io/[project-id]/[build-image-name]
- id: publish to pubsub
  name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      # Get the Git author's email address
      git_author_email=$(git show -s --format='%ae' $COMMIT_SHA)

      # Extract GitHub username from the email address
      git_username=$(echo "$git_author_email" | sed -n 's/\([^.]*\)[+][^.]*@users\.noreply\.github\.com/\1/p')
      
      echo "GitHub username: $git_username"

    

# - id: Docker build
#   name: 'gcr.io/cloud-builders/docker'
#   args: ['build', '-t', '${_REPO_REGION}/${_PROJECT_ID}/${_REPO_NAME}/${_SERVICE_NAME}:${_TAG_NAME}', '.']

# # Push the container image to Artifact Registry
# - id: Container image push
#   name: 'gcr.io/cloud-builders/docker'
#   args: ['push', '${_REPO_REGION}/${_PROJECT_ID}/${_REPO_NAME}/${_SERVICE_NAME}:${_TAG_NAME}']

# - id: Cloud run deploy
#   name: google/cloud-sdk
#   args:
#   - gcloud
#   - run
#   - deploy
#   - ${_SERVICE_NAME}
#   - --image=${_REPO_REGION}/${_PROJECT_ID}/${_REPO_NAME}/${_SERVICE_NAME}:${_TAG_NAME}
#   - --region=${_REGION}
#   - --platform=managed
#   - --service-account=${_SERVICE_ACCOUNT}
#   - --max-instances=5
#   - --memory=512Mi
#   # - --vpc-connector=projects/${_HOST_PROJECT_ID}/locations/${_REGION}/connectors/${_VPC_CONNECTOR}
#   # - --ingress=all
#   #- --ingress=internal-and-cloud-load-balancing
#   # - --vpc-egress=all-traffic
#   - --allow-unauthenticated
#   - --port=80
# timeout: 3660s

# images:
# - ${_REPO_REGION}/${_PROJECT_ID}/${_REPO_NAME}/${_SERVICE_NAME}:${TAG_NAME}

# options:
#   logging: CLOUD_LOGGING_ONLY
  
# substitutions:
#   _REPO_REGION: us-docker.pkg.dev
#   _REPO_NAME: shiv-testing
#   _SERVICE_NAME: testing
#   _REGION: us-central1
#   _SERVICE_ACCOUNT: shiv-testing-account@sureel-test.iam.gserviceaccount.com
#   _PROJECT_ID: sureel-test
#   _TAG_NAME: shiv-image1 
  


  # 'gcr.io/_PROJECT_ID/IMAGE_NAME:TAG'

  # us-docker.pkg.dev/glb-chr-artifactory/shiv-testing:shiv-image
